"""
Business threshold configuration.
Copy to thresholds.py and adjust values for your use case.
"""

SIGNIFICANT_PRICE_DIFF_PCT = 15.0
SWOT_BELOW_RRP_STRENGTH_PCT = 45.0
SWOT_GOOD_QUALITY_STRENGTH_PCT = 55.0
SWOT_DUAL_COVERAGE_STRENGTH_PCT = 55.0
SWOT_CHEAPEST_STRENGTH_PCT = 45.0
SWOT_ABOVE_RRP_WEAKNESS_PCT = 25.0
SWOT_POOR_QUALITY_WEAKNESS_PCT = 15.0
SWOT_MARGIN_UPLIFT_PCT = 15.0
SWOT_CHEAPEST_THREAT_PCT = 35.0
